Thunder/Controllers/MasterCityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Collections.Generic;
using Thunder.DataAccess;
using Thunder.Models;
using Thunder.ViewModel;

namespace Thunder.Controllers
{
    public class MasterCityController : Controller
    {
        private readonly ILogger<MasterCityController> logger;
        private readonly ThunderDB thunderDB;
        private readonly IConfiguration configuration;


        public MasterCityController(ILogger<MasterCityController> _logger, ThunderDB _thunderDB, IConfiguration _configuration)
        {
            logger = _logger;
            thunderDB = _thunderDB;
            configuration = _configuration;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                ViewBag.Cities =  thunderDB.City
                    .Include(table => table.Universities)
                    .ToList();
                return View();
            }
            catch (Exception error)
            {
                logger.LogError(error, "Master City Controller - Index");
                throw;
            }
        }

        public async Task<IActionResult> Sync()
        {
            try
            {
                CityResponseSync cityResponseSync = new CityResponseSync();
                using (HttpClient httpClient = new HttpClient())
                {
                    using (HttpResponseMessage response = await httpClient.GetAsync(configuration.GetValue<string>("ApiUrls:SyncCity")))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        cityResponseSync = JsonConvert.DeserializeObject<CityResponseSync>(apiResponse);
                    }
                }
                List<CityDataSync> cityDataSyncs = new List<CityDataSync>();
                int currentYear = cityResponseSync.data
                    .Select(column => column.tahun)
                    .Distinct()
                    .Max();
                cityDataSyncs = cityResponseSync.data
                    .Where(column => column.tahun == currentYear)
                    .ToList();
                List<City> cities = await thunderDB.City
                    .ToListAsync();
                foreach (CityDataSync cityDataSync in cityDataSyncs)
                {
                    City currentCity = cities
                        .Where(column => column.Id == cityDataSync.kode_kabupaten_kota)
                        .FirstOrDefault();

                    currentCity.EducationIndexScore = cityDataSync.indeks_pendidikan;
                    currentCity.UpdatedDate = DateTime.Now;
                    thunderDB.Entry(currentCity).State = EntityState.Modified;
                    thunderDB.City.Update(currentCity);
                }
                await thunderDB.SaveChangesAsync();
                ViewBag.Cities = thunderDB.City
                    .Include(table => table.Universities)
                    .ToList();
                return View("Index");

            }
            catch (Exception error)
            {
                logger.LogError(error, "Master City Controller - Sync");
                throw;
            }
        }

    }
}

Thunder/Views/MasterCity/Index.cshtml
<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>
				<h2 class="text-white pb-2 fw-bold">Pengelola Kota</h2>
			</div>
            <div class="ml-md-auto py-2 py-md-0">
				<a class="btn btn-white btn-border btn-round mr-2" asp-controller="MasterCity" asp-action="Sync">Sinkronisasi</a>
			</div>

		</div>
	</div>
</div>

<div class="page-inner mt--5">
	<div class="row mt--2 row" id="content">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body row">
					<div class="table-responsive">
						<table id="basic-datatables" class="display table table-striped table-hover" cellspacing="0" width="100%">
							<thead>
                                <tr>
                                    <th>Kode </th>
                                    <th>Nama Kota/Kabupaten</th>
                                    <th>Indeks Pendidikan</th>
                                    <th>Jumlah Universitas Terdaftar</th>
                                </tr>
							</thead>
                            <tbody>
								@foreach (City city in ViewBag.Cities)
								{
									<tr>
										<td>@city.Id</td>
										<td>@city.Name</td>
										<td>@city.EducationIndexScore</td>
										<td>@city.Universities.Count()</td>
									</tr>
								}                            
                            </tbody>
                        </table>
    				</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	$('#basic-datatables').DataTable();
</script>