Thunder/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Thunder.DataAccess;

namespace Thunder.Controllers
{
    public class AboutController : Controller
    {
        private readonly ILogger<AboutController> logger;
        private readonly ThunderDB thunderDB;

        public AboutController(ILogger<AboutController> _logger, ThunderDB _thunderDB)
        {
            logger = _logger;
            thunderDB = _thunderDB;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                ViewBag.Content = System.IO.File.ReadAllText("wwwroot/other/about.txt");
                return View();
            }
            catch (Exception error)
            {
                logger.LogError(error, "About Controller - Index");
                throw;
            }
        }
    }
}

Thunder/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Thunder.DataAccess;
using Thunder.Models;
using Thunder.ViewModel;

namespace Thunder.Controllers
{
    [AllowAnonymous]
    public class AuthController : Controller
    {
        private readonly ILogger<AuthController> logger;
        private readonly ThunderDB thunderDB;

        public AuthController(ILogger<AuthController> _logger, ThunderDB _thunderDB)
        {
            logger = _logger;
            thunderDB = _thunderDB; 
        }

        public async Task<IActionResult> Login()
        {
            try
            {
                AuthenticationProperties properties = new AuthenticationProperties { RedirectUri = Url.Action("Validate") };
                return Challenge(properties, GoogleDefaults.AuthenticationScheme);
            }
            catch (Exception error)
            {
                logger.LogError(error.Message, "Auth Controller - Login Error");
                throw;
            }
        }

        private string GetClaims(List<UserClaim> claims, string key)
        {
            try 
            { 
                return claims.Where(claim => claim.Name == key).FirstOrDefault().Value;
            }
            catch (Exception error)
            {
                logger.LogError(error.Message, "Auth Controller - Get Claims Error");
                throw;
            }
        }

		[Route("Auth/Validate")]
        public async Task<IActionResult> Validate()
        {
            try
            {
                AuthenticateResult result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                List<UserClaim> claims = result.Principal
                    .Identities
                    .FirstOrDefault()
                    .Claims
                    .Select(response => new UserClaim
                    {
                        Issuer = response.Issuer,
                        OriginalIssuer = response.OriginalIssuer,
                        Type = response.Type,
                        Value = response.Value
                    }).ToList();

                User user = thunderDB.User
                    .Where(user => user.Email == GetClaims(claims, "emailaddress"))
                    .FirstOrDefault();

                if (user == null)
                {
                    user = new User();
                    user.CreatedDate = DateTime.Now;
                    user.IsExist = 1;
                    user.RoleId = 1;
                    user.Name = GetClaims(claims, "name");
                    user.Email = GetClaims(claims, "emailaddress");
                    user.Image = GetClaims(claims, "picture");
                    thunderDB.Entry(user).State = Microsoft.EntityFrameworkCore.EntityState.Added;
                    await thunderDB.User.AddAsync(user);
                }
                else
                {
                    user.Name = GetClaims(claims, "name");
                    user.Email = GetClaims(claims, "emailaddress");
                    user.Image = GetClaims(claims, "picture");
                    thunderDB.Entry(user).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    thunderDB.User.Update(user);
                }
                await thunderDB.SaveChangesAsync();

                Role role = thunderDB.Role
                    .Where(column => column.Id == user.RoleId)
                    .FirstOrDefault();

                List<Claim> loggedUser = new List<Claim>();
                loggedUser.Add(new Claim("Id", user.Id.ToString()));
                loggedUser.Add(new Claim("Email", user.Email));
                loggedUser.Add(new Claim("RoleId", user.RoleId.ToString()));
                loggedUser.Add(new Claim("Name", user.Name));
                loggedUser.Add(new Claim("IsExist", user.IsExist.ToString()));
                loggedUser.Add(new Claim("Image", user.Image.ToString()));
                loggedUser.Add(new Claim("Role", role.Name));

                ClaimsIdentity userIdentity = new ClaimsIdentity(loggedUser, CookieAuthenticationDefaults.AuthenticationScheme);
                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(userIdentity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, userPrincipal);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception error)
            {
                logger.LogError(error.Message, "Auth Controller - Google Response");
                throw;
            }
        }

        public async Task<IActionResult> Logout() 
        {
            try
            { 
                await HttpContext.SignOutAsync();
                return RedirectToAction("Index", "Home");
            }
            catch (Exception error)
            {
                logger.LogError(error.Message, "Auth Controller - Logout");
                throw;
            }
        }
    }
}

Thunder/Controllers/FinderController.cs
using MatrixDotNet;
using MatrixDotNet.Extensions.Builder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Thunder.DataAccess;
using Thunder.Models;
using Thunder.ViewModel;

namespace Thunder.Controllers
{
    public class FinderController : Controller
    {

        private readonly ILogger<FinderController> logger;
        private readonly ThunderDB thunderDB;

        public FinderController(ILogger<FinderController> _logger, ThunderDB _thunderDB)
        {
            logger = _logger;
            thunderDB = _thunderDB;
        }

        public async Task<IActionResult> Index()
        {
            try
            {                
                ViewBag.Cities = await thunderDB.City
                    .Include(table => table.Universities)
                    .ToListAsync();
                ViewBag.Facilities = await thunderDB.Facility
                    .ToListAsync();
                return View();
            }
            catch (Exception error)
            {
                logger.LogError(error, "Finder Controller - Index");
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Find(string Cities, string Facilities, string Accreditation, int TuitionFee = 0 )
        {
            try
            {
                if (!thunderDB.Survey.Where(a => a.UserId == User.GetId()).Any())
                {
                    return BadRequest("Survey belum diisi, silahkan isi survey terlebih dahulu");
                }

                List<string> inputCities = JsonConvert.DeserializeObject<List<string>>(Cities);
                List<string> inputAccreditations = JsonConvert.DeserializeObject<List<string>>(Accreditation);
                List<string> inputFacilities = JsonConvert.DeserializeObject<List<string>>(Facilities);
                //List<string> inputPriorities = JsonConvert.DeserializeObject<List<string>>(Priorities);
                int inputTuitionFee = TuitionFee;
                int no = 1;

                //Define Priority
                List<Priority> priorities = new List<Priority>();

                priorities.Add(new Priority(1, "price"));
                priorities.Add(new Priority(2, "city"));
                priorities.Add(new Priority(3, "facility"));
                priorities.Add(new Priority(3, "accreditation"));


                List<University> universities = thunderDB.University
                    .Include(x => x.UniversityFacilities)
                    .Include(x => x.Accreditation)
                    .Include(x => x.City)
                    .ToList();

                List<PriorityRank> priorityRanks = new List<PriorityRank>();
                List<Survey> surveys = thunderDB.Survey.ToList();

                double priceToCity = 1;
                foreach (Survey survey in surveys)
                {
                    priceToCity = priceToCity * Math.Round(survey.PriceToCityValue, 3, MidpointRounding.AwayFromZero);
                }
                priceToCity = Math.Pow(priceToCity, 1.0 / surveys.Count());
                priorityRanks.Add(new PriorityRank(no, "price", "city", priceToCity));
                priorityRanks.Add(new PriorityRank(no, "city", "price", 1 / priceToCity));

                double facilityToPrice = 1;
                foreach (Survey survey in surveys)
                {
                    facilityToPrice = facilityToPrice * Math.Round(survey.FacilityToPriceValue, 3, MidpointRounding.AwayFromZero);
                }
                facilityToPrice = Math.Pow(facilityToPrice, 1.0 / surveys.Count());
                priorityRanks.Add(new PriorityRank(no, "facility", "price", facilityToPrice));
                priorityRanks.Add(new PriorityRank(no, "price", "facility", 1 / facilityToPrice));

                double priceToAccreditation = 1;
                foreach (Survey survey in surveys)
                {
                    priceToAccreditation = priceToAccreditation * Math.Round(survey.PriceToAccreditationValue, 3, MidpointRounding.AwayFromZero);
                }
                priceToAccreditation = Math.Pow(priceToAccreditation, 1.0 / surveys.Count());
                priorityRanks.Add(new PriorityRank(no, "price", "accreditation", priceToAccreditation));
                priorityRanks.Add(new PriorityRank(no, "accreditation", "price", 1 / priceToAccreditation));

                double facilityToCity = 1;
                foreach (Survey survey in surveys)
                {
                    facilityToCity = facilityToCity * Math.Round(survey.FacilityToCityValue, 3, MidpointRounding.AwayFromZero);
                }
                facilityToCity = Math.Pow(facilityToCity, 1.0 / surveys.Count());
                priorityRanks.Add(new PriorityRank(no, "facility", "city", facilityToCity));
                priorityRanks.Add(new PriorityRank(no, "city", "facility", 1 / facilityToCity));

                double accreditationToCity = 1;
                foreach (Survey survey in surveys)
                {
                    accreditationToCity = accreditationToCity * Math.Round(survey.AccreditationToCityValue, 3, MidpointRounding.AwayFromZero);
                }
                accreditationToCity = Math.Pow(accreditationToCity, 1.0 / surveys.Count());
                priorityRanks.Add(new PriorityRank(no, "accreditation", "city", accreditationToCity));
                priorityRanks.Add(new PriorityRank(no, "city", "accreditation", 1 / accreditationToCity));

                double facilityToAccreditation = 1;
                foreach (Survey survey in surveys)
                {
                    facilityToAccreditation = facilityToAccreditation * Math.Round(survey.FacilityToAccreditationValue, 3, MidpointRounding.AwayFromZero);
                }
                facilityToAccreditation = Math.Pow(facilityToAccreditation, 1.0 / surveys.Count());
                priorityRanks.Add(new PriorityRank(no, "facility", "accreditation", facilityToAccreditation));
                priorityRanks.Add(new PriorityRank(no, "accreditation", "facility", 1 / facilityToAccreditation));
                priorityRanks.Add(new PriorityRank(no, "accreditation", "accreditation", 1));
                priorityRanks.Add(new PriorityRank(no, "facility", "facility", 1));
                priorityRanks.Add(new PriorityRank(no, "price", "price", 1));
                priorityRanks.Add(new PriorityRank(no, "city", "city", 1));

                foreach (Priority priority in priorities)
                {
                    foreach (PriorityRank priorityRank in priorityRanks.Where(data => data.Priority2 == priority.Name))
                    {
                        priority.SumPairWise = priority.SumPairWise + priorityRank.Score; 
                    }
                }

                double totalNormalizationScore = 0;
                foreach (PriorityRank priorityRank in priorityRanks)
                {
                    priorityRank.NormalizationScore = Math.Round(priorityRank.Score / priorities.Where(x => x.Name == priorityRank.Priority2).First().SumPairWise, 4, MidpointRounding.AwayFromZero);
                    priorityRank.NormalizationScoreString = $"{priorityRank.Score} / {priorities.Where(x => x.Name == priorityRank.Priority2).First().SumPairWise}";
                    totalNormalizationScore = totalNormalizationScore + priorityRank.NormalizationScore;
                }

                foreach (Priority priority in priorities)
                {
                    //foreach (PriorityRank priorityRank in priorityRanks.Where(data => data.Priority1 == priority.Name))
                    //{
                    //}
                    //priority.Weight = Math.Round(priority.Weight / totalNormalizationScore, 2, MidpointRounding.AwayFromZero);
                        priority.Weight = priorityRanks.Where(x => x.Priority1 == priority.Name).Sum(x => x.NormalizationScore) / priorityRanks.Sum(x => x.NormalizationScore);

                }

                //List City
                double maxEducationIndexScore = universities.Select(p => p.City.EducationIndexScore).DefaultIfEmpty(0).Max();
                double minEducationIndexScore = universities.Select(p => p.City.EducationIndexScore).DefaultIfEmpty(0).Min();
                double scoreIndex = Math.Round((maxEducationIndexScore - minEducationIndexScore), 0, MidpointRounding.AwayFromZero);

                List<CityRank> cityRanks = new List<CityRank>();
                int id = 1;
                foreach (University university1 in universities)
                {
                    foreach (University university2 in universities)
                    {
                        if (university1 != university2)
                        {
                            if (university1.City.EducationIndexScore > university2.City.EducationIndexScore)
                            {
                                cityRanks.Add(new CityRank(id, university1, university2, (Math.Round((university1.City.EducationIndexScore / university2.City.EducationIndexScore)/ scoreIndex, 4, MidpointRounding.ToPositiveInfinity))));
                                id++;
                            }
                        }
                        else
                        {
                            cityRanks.Add(new CityRank(id, university1, university2, 1));
                            id++;
                        }
                    }
                }

                foreach (University university1 in universities)
                {
                    foreach (University university2 in universities)
                    {
                        if (cityRanks.Where(x => x.University1.City == university1.City && x.University2.City == university2.City).Any())
                        {
                            continue;
                        } 

Thunder/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Thunder.DataAccess;

namespace Thunder.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ILogger<ProfileController> logger;
        private readonly ThunderDB thunderDB;

        public ProfileController(ILogger<ProfileController> _logger, ThunderDB _thunderDB)
        {
            logger = _logger;
            thunderDB = _thunderDB;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                return View();
            }
            catch (Exception error)
            {
                logger.LogError(error, "Profile Controller - Index");
                throw;
            }
        }
    }
}

Thunder/Views/Shared/Sample.cshtml
<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>
				<h2 class="text-white pb-2 fw-bold">Dashboard</h2>
				<h5 class="text-white op-7 mb-2">Premium Bootstrap 4 Admin Dashboard</h5>
			</div>
			<div class="ml-md-auto py-2 py-md-0">
				<a href="#" class="btn btn-white btn-border btn-round mr-2">Manage</a>
				<a href="#" class="btn btn-secondary btn-round">Add Customer</a>
			</div>
		</div>
	</div>
</div>
<div class="page-inner mt--5">
	
	<div class="row mt--2">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="card-head-row">
						<div class="card-title">User Statistics</div>
						<div class="card-tools">
							<a href="#" class="btn btn-info btn-border btn-round btn-sm mr-2">
								<span class="btn-label">
									<i class="fa fa-pencil"></i>
								</span>
								Export
							</a>
							<a href="#" class="btn btn-info btn-border btn-round btn-sm">
								<span class="btn-label">
									<i class="fa fa-print"></i>
								</span>
								Print
							</a>
						</div>
					</div>
				</div>
				<div class="card-body">


				</div>
			</div>
		</div>		
	</div>
	
</div>

Thunder/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
@functions{
	private bool IsAuthenticated()
	{
		return User.Claims.Any();
	}

	public string GetUserClaim(string type)
	{
		return User.Claims.Where(x => x.Type == type).Select(x => x.Value).FirstOrDefault();
	}

	public string GetImage()
	{
		if (IsAuthenticated())
		{
			return GetUserClaim("Image");
		}
		else
		{
				return $"img/profile.jpg";
		}
	}	
}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>@Configuration.GetSection("Template")["SiteName"]</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
	<link rel="icon" href="~/img/icon.ico" type="image/x-icon"/>
	<script src="~/js/plugin/webfont/webfont.min.js"></script>
	<script>
		WebFont.load({
			google: {"families":["Lato:300,400,700,900"]},
			custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['css/fonts.min.css']},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>
	<link rel="stylesheet" href="~/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/css/atlantis.css">

		<!--   Core JS Files   -->
	<script src="~/js/core/jquery.3.2.1.min.js"></script>
	<script src="~/js/core/popper.min.js"></script>
	<script src="~/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>

	<script src="~/js/core/bootstrap.min.js"></script>
	<!-- jQuery UI -->
	<script src="~/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
	<script src="~/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
	<!-- jQuery Scrollbar -->
	<script src="~/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
	<!-- Moment JS -->
	<script src="~/js/plugin/moment/moment.min.js"></script>
	<!-- Datatables -->
	<script src="~/js/plugin/datatables/datatables.min.js"></script>
	<!-- Bootstrap Notify -->
	<script src="~/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
	<!-- Bootstrap Toggle -->
	<script src="~/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
	<!-- Dropzone -->
	<script src="~/js/plugin/dropzone/dropzone.min.js"></script>
	<!-- DateTimePicker -->
	<script src="~/js/plugin/datepicker/bootstrap-datetimepicker.min.js"></script>
	<!-- Bootstrap Tagsinput -->
	<script src="~/js/plugin/bootstrap-tagsinput/bootstrap-tagsinput.min.js"></script>
	<!-- Bootstrap Wizard -->
	<script src="~/js/plugin/bootstrap-wizard/bootstrapwizard.js"></script>
	<!-- jQuery Validation -->
	<script src="~/js/plugin/jquery.validate/jquery.validate.min.js"></script>
	<!-- Summernote -->
	<script src="~/js/plugin/summernote/summernote-bs4.min.js"></script>
	<!-- Select2 -->
	<script src="~/js/plugin/select2/select2.full.min.js"></script>
	<!-- Owl Carousel -->
	<script src="~/js/plugin/owl-carousel/owl.carousel.min.js"></script>
	<!-- Magnific Popup -->
	<script src="~/js/plugin/jquery.magnific-popup/jquery.magnific-popup.min.js"></script>
	<!-- Atlantis JS -->
	<script src="~/js/atlantis.min.js"></script>
	<!-- Site JS -->
	<script src="~/js/site.js"></script>
</head>
<body data-background-color = "@Configuration.GetSection("Template")["BodyColor"]">
	<div class="wrapper">
		<div class="main-header">
			<div class="logo-header" data-background-color= "@Configuration.GetSection("Template")["LogoHeaderColor"]">				
				<a asp-controller="Home" asp-action="Index" class="logo">
					<img src="~/img/logo.svg" alt="navbar brand" class="navbar-brand">
				</a>
				<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="icon-menu"></i>
					</span>
				</button>
				<button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
				<div class="nav-toggle">
					<button class="btn btn-toggle toggle-sidebar">
						<i class="icon-menu"></i>
					</button>
				</div>
			</div>
			<nav class="navbar navbar-header navbar-expand-lg" data-background-color = "@Configuration.GetSection("Template")["NavBarHeaderColor"]">							
				<partial name="_NavigationBar" />					
			</nav>				
		</div>

		<div class="sidebar sidebar-style-2" data-background-color = "@Configuration.GetSection("Template")["SideBarColor"]">			
		@if (IsAuthenticated())
		{
			<div class="sidebar-wrapper scrollbar scrollbar-inner">
				<div class="sidebar-content">
					<div class="user">
						<div class="avatar-sm float-left mr-2">
							<img src="@GetImage()" referrerpolicy="no-referrer" alt="..." class="avatar-img rounded-circle">
						</div>
						<div class="info">
							<a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
								<span>
									@GetUserClaim("Name")
									<span class="user-level">@GetUserClaim("Role")</span>
								</span>
							</a>
							<div class="clearfix"></div>							
						</div>
					</div>
					<ul class="nav nav-primary">
						<partial name="_Menu" />					
					</ul>
				</div>
			</div>
		}
		</div>


		<div class="main-panel">
			<div class="container">
				@RenderBody()
			</div>

			<footer class="footer">
				<div class="container-fluid">
					<nav class="pull-left">
						<ul class="nav">
							<li class="nav-item">
								<a class="nav-link" href="@Configuration.GetSection("Template")["CopyrightUrl"]">
									@Configuration.GetSection("Template")["CopyrightName"]
								</a>
							</li>
						</ul>
					</nav>
					<div class="copyright ml-auto">
						@Configuration.GetSection("Template")["ReleaseYear"], by <a href="@Configuration.GetSection("Template")["DeveloperUrl"]"> @Configuration.GetSection("Template")["DeveloperName"] </a>
					</div>				
				</div>
			</footer>
		</div>				
	</div>
</body>
	
</html>

@await RenderSectionAsync("Scripts", required: false)

Thunder/Views/Shared/_Menu.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
@functions{
	private bool IsAuthenticated()
	{
		return User.Claims.Any();
	}

	public string GetUserClaim(string type)
	{
		return User.Claims.Where(x => x.Type == type).Select(x => x.Value).FirstOrDefault();
	}

	public string GetImage()
	{
		if (IsAuthenticated())
		{
			return GetUserClaim("Image");
		}
		else
		{
				return $"img/profile.jpg";
		}
	}	
}


@if (GetUserClaim("Role") == "Admin")
{
	<li class="nav-section">
		<span class="sidebar-mini-icon">
			<i class="fa fa-ellipsis-h"></i>
		</span>
		<h4 class="text-section">Menu Admin</h4>
	</li>

	<li class="nav-item active">
		<a data-toggle="collapse" href="#masterSetting" class="collapsed" aria-expanded="false">
			<i class="fas fa-cog"></i>
			<p>Pengaturan</p>
			<span class="caret"></span>
		</a>
		<div class="collapse" id="masterSetting">
			<ul class="nav nav-collapse">
				<li>
					<a asp-controller="MasterUser" asp-action="Index">
						<span class="sub-item">Pengguna</span>
					</a>
				</li>								
				<li>
					<a asp-controller="MasterUniversity" asp-action="Index">
						<span class="sub-item">Universitas</span>
					</a>
				</li>		
				<li>
					<a asp-controller="MasterFacility" asp-action="Index">
						<span class="sub-item">Fasilitas</span>
					</a>
				</li>	
				<li>
					<a asp-controller="MasterCity" asp-action="Index">
						<span class="sub-item">Kota</span>
					</a>
				</li>	
				<li>
					<a asp-controller="Survey" asp-action="Result">
						<span class="sub-item">Hasil Survey</span>
					</a>
				</li>	
			</ul>
		</div>
	</li>
	
}

<li class="nav-section">
	<span class="sidebar-mini-icon">
		<i class="fa fa-ellipsis-h"></i>
	</span>
	<h4 class="text-section">Menu Utama</h4>
</li>

<li class="nav-item active">
	<a asp-controller="University" asp-action="Index">
		<i class="fas fa-home"></i>
		<p>Universitas</p>
	</a>
</li>	

<li class="nav-item active">
	<a asp-controller="Survey" asp-action="Index">
		<i class="fas fa-list"></i>
		<p>Survey Prioritas</p>
	</a>
</li>	

									
<li class="nav-item active">
	<a asp-controller="About" asp-action="Index">
		<i class="fas fa-list"></i>
		<p>Tentang</p>
	</a>
</li>	

<li class="nav-item active">
	<a asp-controller="Finder" asp-action="Index">
		<i class="fas fa-search"></i>
		<p>Pencarian Kampus</p>
	</a>
</li>	
	

Thunder/Views/Shared/_NavigationBar.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
@functions{
	private bool IsAuthenticated()
	{
		return User.Claims.Any();
	}

	public string GetUserClaim(string type)
	{
		return User.Claims.Where(x => x.Type == type).Select(x => x.Value).FirstOrDefault();
	}

	public string GetImage()
	{
		if (IsAuthenticated())
		{
			return GetUserClaim("Image");
		}
		else
		{
				return $"img/profile.jpg";
		}
	}	
}

<div class="container-fluid">
	<div class="collapse" id="search-nav">
		<div class="navbar-left navbar-form nav-search mr-md-3" hidden>
			<div class="input-group">
				<div class="input-group-prepend">
					<button type="submit" class="btn btn-search pr-1">
						<i class="fa fa-search search-icon"></i>
					</button>
				</div>
				<input type="text" placeholder="Pencarian ..." id="keyword" class="form-control">
			</div>
		</div>
	</div>
	<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
		<li class="nav-item toggle-nav-search hidden-caret">
			<a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
				<i class="fa fa-search"></i>
			</a>
		</li>

		<li class="nav-item dropdown hidden-caret">
			<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
				<div class="avatar-sm">
					<img src="@GetImage()" referrerpolicy="no-referrer" class="avatar-img rounded-circle">
				</div>
			</a>
			<ul class="dropdown-menu dropdown-user animated fadeIn">
				<div class="dropdown-user-scroll scrollbar-outer">
					@if (IsAuthenticated())
					{
						<li>
							<div class="user-box">
								<div class="avatar-lg"><img src="@GetImage()" alt="image profile" class="avatar-img rounded"></div>
									<div class="u-text">
									<h4>@GetUserClaim("Name")</h4>
									<p class="text-muted">@GetUserClaim("Email")</p>
								</div>								   										
							</div>
						</li>
						<div class="dropdown-divider"></div>
						<li>
							<a class="dropdown-item" asp-controller="Profile" asp-action="Index">Profil Saya</a>
							<a class="dropdown-item"  asp-controller="Auth" asp-action="Logout" >Logout</a>
						</li>
					}
					else
					{								
						<a class="dropdown-item" asp-controller="Auth" asp-action="Login">Login</a>
					}
				</div>
			</ul>
		</li>							
	</ul>
</div>